// Generated by CoffeeScript 1.7.1
(function() {
  var Core, K, root,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  K = {};

  root.K = K;

  Core = (function() {
    Core.prototype.idCounter = 0;

    function Core() {
      this.id = this.idCounter++;
      this.children = {};
    }

    Core.prototype.add = function(child) {
      child.parent = this;
      return this.children[child.id] = child;
    };

    Core.prototype.isParentOf = function(child) {
      if (__indexOf.call(this.children, child) >= 0) {
        return true;
      }
    };

    Core.prototype.isChildOf = function(parent) {
      if (parent === this.parent) {
        return true;
      }
    };

    return Core;

  })();

  root.Core = Core;

}).call(this);
